language: python

python:
  - "2.7"
  - "pypy"

install:
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt
  - pip install coveralls

script: make all BINROOT=

after_success:
  coveralls

